package variables;

public class Dimensions
{
	/*
	 * Initialize the dimensions for the autonomous mode
	 * 
	 * Distances must be in inches
	 */
	
	public static final double RETRIEVE_ZONE_DEPTH = 42, KEY_DEPTH = 52, DIST_TO_BASELINE = 84,
			LENGTH_TO_OBJECTIVE = 0 /* ??? */, PEGBASE_ALLIANCEWALL_TRIANGLE_BASE = 228.492,
			PEGBASE_TO_BARRIER = 131.475, ROBOT_LENGTH = 30.0, DIST_TO_DECK = 114.3, HOOK_LENGTH = 10.5,
			PEGBASE_ALLIANCEWALL_TRIANGLE_HYPOTENUSE = 263.84,
			RETRIEVAL_ALLIANCE_ANGLE = 63.32 /* MAYBE INACCURATE */,
			KEY_ALLIANCE_ANGLE = 46.25 /* MAYBE INACCURATE */, CORNER_TO_BOILER = 20.98,
			KEYZONE_ALLIANCE_INTERSECT = 100.516, RETRIEVAL_ALLIANCE_INTERSECT = 83.165;
}
